#!/bin/sh -e

# Install .vimrc and .gvimrc in the home directory
VIMFILES=`pwd`
[ -d "$HOME" ] && cd "$HOME"
[ -r "$VIMFILES"/.vimrc ] && ln -sf "$VIMFILES"/.vimrc $HOME/.vimrc
[ -r "$VIMFILES"/.gvimrc ] && ln -sf "$VIMFILES"/.gvimrc $HOME/.gvimrc

# Get all git submodules
cd "$VIMFILES"
git submodule update --init
git submodule foreach 'git checkout master; git pull'

# Create empty directories
mkdir -p .haddock_index .undodir
