#!/bin/sh -e

# Install .vimrc and .gvimrc in the home directory
VIMFILES=`pwd`
[ -d "$HOME" ] && cd "$HOME"

# Get all git submodules
cd "$VIMFILES"
git submodule update --init --recursive
git submodule foreach --recursive 'git checkout master; git pull'

# Create empty directories
mkdir -p .haddock_index .undodir
