#!/bin/sh

set -eu

# Set up nvim
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -sf ~/.vim $XDG_CONFIG_HOME/nvim

# Get all git submodules
: ${VIMFILES:=$(pwd)}
cd "$VIMFILES"
git submodule update --init --recursive
git submodule foreach --recursive 'git checkout master; git pull'

# Create empty directories
mkdir -p .haddock_index .undodir
